### ISSUE TITLE
Check out why the SRI for the minified swiper js bundle hosted on unpkg.com has changed.

### ISSUE THREAD

**Issue by 4855062503** [zap-me/premio_cms#22]
Upon a get request to both Swiper cdn's, a 302 status code was returned in the response body, as the SRI from unpkg.com had been changed for both resources yet their version number remains unchanged.

This thus broke our current styling + js functionality as a Swiper object is declared in our js before lazy-loading, leaflet etc are used.

CDNS: 

https://unpkg.com/swiper/swiper-bundle.min.css
https://unpkg.com/swiper/swiper-bundle.min.js

**Comment by djpnewton** [comment]
I think you should link to a specific version like this: https://unpkg.com/swiper@6.5.0/swiper-bundle.min.js
